version: '3.8'
services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "3010:3010"  
    environment:
      DATABASE_URL: postgres://user:password@db:5432/proscom
    depends_on:
      - db 

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proscom
    ports:
      - "5442:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
