-- AlterTable
ALTER TABLE "reasons" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "services" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0);

-- AlterTable
ALTER TABLE "tickets" ALTER COLUMN "start_time" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "end_time" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(0);
